import { params, type Parameters } from '../presets/presets';
export function mountUI(){
 document.querySelector('#app')!.innerHTML=`
 <main class="experiment">
 <header class="masthead"><h1 class="wordmark">Pizza<span>Physics</span><i aria-hidden="true">.</i></h1><div class="intro"><p>Good dough. Long pull.</p><span>An interactive Neapolitan margherita.</span></div><span class="project-tag">PULL / STRETCH / REPEAT</span></header>
 <section class="stage" aria-label="Pizza interaction"><div class="stage-caption"><span>NEAPOLITAN MARGHERITA</span><span>Made to be pulled apart.</span></div><canvas id="scene" tabindex="0" aria-label="Interactive Neapolitan pizza. Drag a slice to stretch the mozzarella. Drag empty space to orbit, pinch or scroll to zoom. Keyboard: Space to grab or release, arrows to move, Page Up and Page Down to lift or lower."></canvas><div class="pull-hint" id="hint"><span class="hint-mark" aria-hidden="true">↗︎</span><span>Pick a slice. See how far it goes.</span></div></section>
 <div class="stage-actions"><span class="gesture-note">Drag to pull · Empty space to orbit · Pinch to zoom</span><div class="view-actions"><button id="camera-reset" title="Reset camera (C)">Reset view</button><button id="hold" aria-pressed="false" title="Keep a slice suspended after release (H)">Hold slice</button><button id="reset" aria-label="Reset pizza and cheese strands">Fresh start <span aria-hidden="true">↻</span></button></div></div>
 <section class="telemetry" aria-label="Live measurements"><div class="section-heading"><span class="indicator"></span> THE PULL, IN NUMBERS</div><dl><div><dt>Stretch</dt><dd><span id="stretch">0</span><small>%</small></dd></div><div><dt>Longest strand</dt><dd><span id="length">0</span><small>mm</small></dd></div><div><dt>Connections</dt><dd id="active">0</dd></div><div class="secondary"><dt>Dough bend</dt><dd><span id="bend">0</span><small>°</small></dd></div></dl><div class="integrity"><div><span>Connections remaining</span><span id="integrity">100%</span></div><div class="track"><i id="integrity-bar"></i></div></div><p id="status" role="status">MOZZARELLA INTEGRITY NOMINAL</p></section>
 <aside class="controls"><div class="controls-intro"><span class="small-label">THE INGREDIENTS OF A GOOD PULL</span><h2>Make it<br><em>stretch.</em></h2><p>Soft dough, molten mozzarella.<br>A little tension changes everything.</p></div><button class="controls-toggle" aria-expanded="true" aria-controls="control-body"><span>Adjust the feel</span><span class="toggle-symbol">−</span></button><div id="control-body"></div><p class="specimen-note">Always Neapolitan.<br><span>Tomato · Fior di latte · Basil</span></p></aside>
 <footer><span>PIZZA PHYSICS <i>—</i> A little food for curiosity.</span><span class="performance"><span id="fps">—</span> FPS <i>/</i> <span id="physics">—</span> MS PHYSICS</span></footer>
 <div id="loading" class="loading"><div>PIZZA PHYSICS<span>.</span></div><p id="loading-message">HEATING OVEN</p><i></i></div>
 <div id="error" hidden><h2>The oven needs a different browser.</h2><p>This experiment needs WebGL 2 or WebGPU. Try a current browser with hardware acceleration enabled.</p><button onclick="location.reload()">TRY AGAIN</button></div>
 </main>`;
 const controls:[keyof Parameters,string,number,number,string][]=[['mozzarella','MOZZARELLA AMOUNT',50,200,'%'],['stretch','CHEESE STRETCH',0,100,'%'],['strength','CHEESE STRENGTH',0,100,'%'],['viscosity','CHEESE VISCOSITY',0,100,'%'],['stiffness','CRUST STIFFNESS',0,100,'%'],['gravity','GRAVITY',0,100,'%'],['temperature','TEMPERATURE',20,100,'°C']];
 const panel=document.querySelector('#control-body')!;
 panel.innerHTML=controls.map(([key,label,min,max,unit])=>`<div class="control-row"><label for="${key}-input">${label}</label><output for="${key}-input" id="${key}-output">${params[key]}${unit}</output><input id="${key}-input" type="range" min="${min}" max="${max}" value="${params[key]}" aria-label="${label.toLowerCase()}"></div>`).join('');
 panel.firstElementChild!.insertAdjacentHTML('afterend',`<div class="control-row seed-row"><label for="mozzarella-seed">MOZZARELLA SEED</label><div class="seed-actions"><input id="mozzarella-seed" type="number" min="0" max="999999" step="1" value="0" inputmode="numeric" aria-label="Mozzarella placement seed"><button id="shuffle-mozzarella" type="button" aria-label="Randomize mozzarella placement">SHUFFLE</button></div></div>`);
 function sync(){for(const [key,,min,max,unit] of controls){const input=document.getElementById(`${key}-input`) as HTMLInputElement;input.value=String(params[key]);input.style.setProperty('--fill',`${(params[key]-min)/(max-min)*100}%`);document.getElementById(`${key}-output`)!.textContent=`${params[key]}${unit}`;}}
 for(const [key] of controls)document.getElementById(`${key}-input`)!.addEventListener('input',e=>{params[key]=Number((e.target as HTMLInputElement).value);sync();});
 const toggle=document.querySelector('.controls-toggle')!;
 function expand(value:boolean){toggle.setAttribute('aria-expanded',String(value));document.querySelector('.controls')!.classList.toggle('collapsed',!value);document.querySelector('.toggle-symbol')!.textContent=value?'−':'+';}
 toggle.addEventListener('click',()=>expand(toggle.getAttribute('aria-expanded')!=='true'));if(innerWidth<=900)expand(false);sync();
 return {sync};
}
